language: go
sudo: required
go:
  - 1.8
  - tip

notifications:
  email: false

before_install:
    - go get github.com/Shopify/sarama
    - go get github.com/bitly/go-nsq
    - go get golang.org/x/net/ipv4
    - go get golang.org/x/net/ipv6
script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - sudo go test -v ./... -timeout 1m
  - make build
